### ISSUE TITLE
undeclared identifier errors 

### ISSUE THREAD

**Issue by imranpopz** [Cosmic-OS/platform_frameworks_base#23]
frameworks/base/services/core/jni/com_android_server_AlarmManagerService.cpp:427:61: error: use of undeclared identifier 'CLOCK_POWEROFF_ALARM'
        if ((fds[i] < 0) && (android_alarm_to_clockid[i] == CLOCK_POWEROFF_ALARM)) {

**Comment by sagarshah1729** [comment]
Discontinued Branch!

**Comment by sagarshah1729** [comment]
Discontinued Branch!
